# org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.jvmargs=-Xmx6g -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g
# Activa la ejecución paralela en módulos desacoplados
org.gradle.parallel=true
# Define la concurrencia máxima (Ideal = número de cores lógicos)
org.gradle.workers.max=8
# Aceleradores nativos de Caché
org.gradle.caching=true
org.gradle.configuration-cache=true
# Evita recompilaciones en cascada por recursos UI
android.nonTransitiveRClass=true
# Desactiva la regeneración de Clases R estáticas constantes
android.defaults.buildFeatures.resValues=false
# Librerias modernas AndroidX no requieren esta sobrecarga
android.enableJetifier=false
# Activa la compilación incremental
kotlin.incremental=true
# When enabled, the Configuration Cache allows Gradle to skip the configuration
# phase entirely if nothing that affects the build configuration (such as build scripts)
# has changed. Additionally, Gradle applies performance optimizations to task execution.
# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
